[versions]
aboutLibraries = "13.1.0"
agp = "8.13.0"
comGoogleDevtoolsKsp = "2.2.20-2.0.4"
composeBom = "2025.10.01"
coreSplashscreen = "1.0.1"
kotlin = "2.2.21"
material3 = "1.4.0"
materialIconsExtended = "1.7.8"
navigationCompose = "2.9.5"
room = "2.8.3"
roomCompiler = "2.8.3"
roomRuntime = "2.8.3"
serialization = "2.1.21"
slf4jApi = "2.0.17"
slf4jNop = "2.0.17"
sshd-sftp = "2.16.0"

[libraries]
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jApi" }
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4jNop" }
sshd-sftp = { group = "org.apache.sshd", name = "sshd-sftp", version.ref = "sshd-sftp" }

[plugins]
aboutlibraries-plugin-android = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }
android-application = { id = "com.android.application", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "comGoogleDevtoolsKsp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# Used for kotlin() plugin directive in build.gradle.kts, although it may appear as unused
plugin-serialization = { id = "plugin.serialization", version.ref = "serialization" }
